/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OpticalShopSystem;

/**
 *
 * @author Administrator
 */

// NOTES: 
// Subject to change
// The difference between DraftInvView and Inview2
// DraftInvView: Jframe layout set GridBagLayout, there is no jPanel that places the 3 jPanels
// Mas clean sigruo ang DraftInvView..

// IMPORTS 
import org.json.simple.*;
import org.json.simple.parser.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;

public class DraftInvView extends javax.swing.JFrame {
    // Initialize String filepath, JSONParser, JSONObject, JSONArray

    private static String fileFrameMaterial = "src\\javaapplication1\\frame_material.json";
    private static String fileFrameLenses = "src\\javaapplication1\\frame_lenses.json";
    private static JSONParser jsonParser1 = new JSONParser();
    private static JSONParser jsonParser2 = new JSONParser();
    private static JSONObject record1 = new JSONObject();
    private static JSONObject record2 = new JSONObject();
    private static JSONArray userlist1 = new JSONArray();
    private static JSONArray userlist2 = new JSONArray();

    /**
     * Creates new form InvView
     */
    public DraftInvView() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        loadUserData();
    }
    
    // upgrade lens and frame only have prices, have quantity
    
    // each customer has an ID !!! 
    // ID is used in appointment record 
    
    // PRESCRIPTION ( Many jsonObject )
    // OD right eye { SPH, CYL, AXIS IPD 
    // OS left eye { SPH, CYL, AXIS IPD 
    
    // Purchase record will calculate the lens and frame prices 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InvView");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Frame Material", "Stock", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 657;
        gridBagConstraints.ipady = 671;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OptometriByte");
        jPanel2.add(jLabel1);

        jButton1.setText("VIEW ITEMS");
        jPanel2.add(jButton1);

        jButton2.setText("ADD ITEMS");
        jPanel2.add(jButton2);

        jButton3.setText("EDIT ITEMS");
        jPanel2.add(jButton3);

        jButton4.setText("DELETE ITEMS");
        jPanel2.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.ipady = 265;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jButton5.setText("BACK TO HOME");
        jPanel3.add(jButton5);

        jButton6.setText("LOG OUT");
        jPanel3.add(jButton6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(141, 0, 0, 0);
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadUserData() {
        try (FileReader reader = new FileReader(fileFrameMaterial)) {
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(reader);

            // Extract the outer object
            JSONObject eyeglassMaterials = (JSONObject) jsonObject.get("eyeglass_frame_materials");

            // Extract both metal and plastic frame materials
            JSONArray metalFrames = (JSONArray) eyeglassMaterials.get("metal");
            JSONArray plasticFrames = (JSONArray) eyeglassMaterials.get("plastic");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            // Add metal frames
            for (Object obj : metalFrames) {
                JSONObject frame = (JSONObject) obj;
                model.addRow(new Object[]{frame.get("frame_material"), frame.get("stock"), frame.get("price")});
            }

            // Add plastic frames
            for (Object obj : plasticFrames) {
                JSONObject frame = (JSONObject) obj;
                model.addRow(new Object[]{frame.get("frame_material"), frame.get("stock"), frame.get("price")});
            }

        } catch (IOException | ParseException e) {
            e.printStackTrace();
            System.out.println("Error loading JSON data: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DraftInvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DraftInvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DraftInvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DraftInvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DraftInvView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
